-- =========================================
--  SCHEMA DO BANCO - Avaliador Didático
--  Tabelas: opcoes, perguntas, questionarios , tipos_pergunta, resultado, usuarios
-- =========================================

-- =========================================
-- Tabela: opcoes
-- =========================================
create table if not exists public.opcoes (
  id bigint generated by default as identity primary key,
  texto text not null,
  ordem integer not null,
  created_at timestamptz default now()
);

-- =========================================
-- Tabela: perguntas
-- =========================================
create table if not exists public.perguntas (
  id bigint generated by default as identity primary key,
  questionario_id bigint not null,
  texto text not null,
  created_at timestamptz default now(),
  tipo_id bigint
);

-- =========================================
-- Tabela: questionarios
-- =========================================
create table if not exists public.questionarios (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descricao text,
  created_at timestamptz default now()
);

-- =========================================
-- Tabela: tipos_pergunta
-- =========================================
create table if not exists public.tipos_pergunta (
  id bigint primary key,
  nome text not null
);

-- =========================================
-- Tabela: resultado
-- =========================================
create table if not exists public.resultado (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null,
  questionario_id bigint not null,
  created_at timestamptz default now(),
  arquivo text not null,
  thumbnail text
);

-- =========================================
-- Tabela: usuarios
-- =========================================

create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  nome text not null,
  created_at timestamptz default now(),
  faculdade varchar,
  telefone_cel varchar,
  telefone_zap varchar,
  cpf varchar,
  email varchar,
  senha_hash varchar,
  criado_em timestamp default now(),
  auth_user_id uuid
);
